version: "3"
services:
  ganache:
    build:
      context: .
      dockerfile: Dockerfile.ganache
    ports:
      - "8545:8545"

  mysqldb:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql

  api:
    build: 
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - ganache
    volumes:
      - ./shareimmo-api:/shareimmo-api

  ihm:
    build: 
      dockerfile: Dockerfile
      context: ./shareimmo-ihm
    ports:
      - "3000:80"
    depends_on:
      - api
    volumes:
      - ./shareimmo-ihm:/shareimmo-ihm

volumes: 
  db: